api = "0.4"

[buildpack]
id = "fagiani/nodejs-yarn"
version = "0.2.0"
name = "Yarn Buildpack"
homepage = "https://github.com/fagiani/nodejs-yarn-buildpack"
description = "Runs Yarn after nodejs install"
keywords = ["nodejs", "node", "yarn", "install", "javascript"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
